### ISSUE TITLE
Native ES6 Module support

### ISSUE THREAD

**Issue by 75lb** [SheetJS/printj#3]
Any plans to release a native ES6 Module we can use directly in modern browsers?

E.g.
```
import printj from './node_modules/printj/printj.js'
```

**Comment by SheetJSDev** [comment]
We don't plan on removing the ES5/CJS bundle that currently exists.  We use this in various sites that are built with webpack or rollup with the relevant CJS loader, so the only real case that needs an ES6-export version is the browser script module loader.

We could additionally add an ES6 module that would export the `sprintf` and `vsprintf` functions directly (for consistency with the browser, it would have to be called `printj.mjs`).  This is actually pretty easy since the whole thing is built from smaller scripts anyway.

The usage would probably look like:

```js
import { sprintf } from './node_modules/printj/printj.mjs'
```

**Comment by 75lb** [comment]
OK, thanks.. well, in the meantime if anyone else would like to use `printj` in a native ES6 web app, [here is a module](https://gist.github.com/75lb/2af553f67d921aa5ce4111825007cc18) you can use until printj supports native ES6 modules.

**Comment by SheetJSDev** [comment]
Included as `printj.mjs` in the repo and npm bundle.

https://oss.sheetjs.com/printj/tests/mjs.html is a demo (check the source, it's unminified)

https://plnkr.co/edit/yTANwhsAoStCw5dQoqwC?p=preview is a live version using unpkg:

```js
import { sprintf } from 'https://unpkg.com/printj@1.2.0/printj.mjs';
sprintf("Hello %s", "World!");
```

**Comment by 75lb** [comment]
works great, thanks! 👍

**Comment by mahadev-Pandhare** [comment]
Is sheetjs pro version support to ES6(ES2015) for angular 12 development by using node modules
